// Conformance tests for tessera_dart against the reference known-answer
// vectors (tests/vectors/kat.json, generated by the Python reference), plus
// enroll->unlock round-trips proving the write side.
//
// Runs headlessly with `dart test`: libsodium is loaded from
// $TESSERA_LIBSODIUM if set, otherwise from common system locations.
// (Flutter apps initialize via package:sodium_libs instead.)
//
// Not covered here: the container (secretstream) — not yet ported; its
// primitive parity is validated by ports/dart_spike.

import 'dart:convert';
import 'dart:ffi';
import 'dart:io';
import 'dart:typed_data';

import 'package:sodium/sodium_sumo.dart';
import 'package:test/test.dart';

import '../lib/tessera_dart.dart';

Uint8List hexDecode(String s) {
  final out = Uint8List(s.length ~/ 2);
  for (var i = 0; i < out.length; i++) {
    out[i] = int.parse(s.substring(i * 2, i * 2 + 2), radix: 16);
  }
  return out;
}

String hexEncode(List<int> b) =>
    b.map((x) => x.toRadixString(16).padLeft(2, '0')).join();

Future<SodiumSumo> initSodium() {
  final candidates = [
    if (Platform.environment['TESSERA_LIBSODIUM'] != null)
      Platform.environment['TESSERA_LIBSODIUM']!,
    '/home/user/software/miniforge3/lib/libsodium.so.26',
    'libsodium.so.26',
    'libsodium.so',
    '/usr/lib/x86_64-linux-gnu/libsodium.so.23',
  ];
  Object? lastErr;
  for (final c in candidates) {
    try {
      return SodiumSumoInit.init(() => DynamicLibrary.open(c));
    } catch (e) {
      lastErr = e;
    }
  }
  throw StateError('could not load libsodium: $lastErr');
}

void main() {
  late final SodiumSumo sodium;
  late final Map<String, dynamic> kat;

  setUpAll(() async {
    sodium = await initSodium();
    final katFile = File('../../tests/vectors/kat.json');
    kat = jsonDecode(katFile.readAsStringSync()) as Map<String, dynamic>;
  });

  test('argon2id', () {
    for (final c in (kat['argon2id'] as List).cast<Map<String, dynamic>>()) {
      final pw = hexDecode(c['password_hex']);
      final key = sodium.crypto.pwhash(
        outLen: c['hash_len'] as int,
        password: Int8List.view(pw.buffer, pw.offsetInBytes, pw.length),
        salt: hexDecode(c['salt_hex']),
        opsLimit: c['opslimit'] as int,
        memLimit: c['memlimit'] as int,
        alg: CryptoPwhashAlgorithm.argon2id13,
      );
      expect(hexEncode(key.extractBytes()), c['output_hex'],
          reason: 'ops=${c['opslimit']} mem=${c['memlimit']}');
      key.dispose();
    }
  });

  test('reduce_mod_p', () {
    for (final c in (kat['reduce_mod_p'] as List).cast<Map<String, dynamic>>()) {
      expect(reduceModP(hexDecode(c['input_hex'])).toString(),
          c['output_decimal']);
    }
  });

  test('blake2b_kdf', () {
    for (final c in (kat['blake2b_kdf'] as List).cast<Map<String, dynamic>>()) {
      final key = sodium.crypto.genericHash(
        outLen: 32,
        message: Uint8List.fromList([
          ...hexDecode(c['domain_hex']),
          ...hexDecode(c['salt_hex']),
          ...hexDecode(c['secret_hex']),
        ]),
      );
      expect(hexEncode(key), c['key_hex']);
    }
  });

  test('xchacha20poly1305', () {
    for (final c
        in (kat['xchacha20poly1305'] as List).cast<Map<String, dynamic>>()) {
      final key = SecureKey.fromList(sodium, hexDecode(c['key_hex']));
      final res = sodium.crypto.aeadXChaCha20Poly1305IETF.encryptDetached(
        message: hexDecode(c['plaintext_hex']),
        nonce: hexDecode(c['nonce_hex']),
        key: key,
        additionalData: hexDecode(c['aad_hex']),
      );
      expect(hexEncode(res.cipherText), c['ciphertext_hex']);
      expect(hexEncode(res.mac), c['tag_hex']);
      key.dispose();
    }
  });

  test('field', () {
    final f = kat['field'] as Map<String, dynamic>;
    expect(P.toString(), f['P_decimal']);
    final coeffs = (f['poly_eval']['coeffs_decimal'] as List)
        .map((e) => BigInt.parse(e as String))
        .toList();
    for (final pt in (f['poly_eval']['points'] as List)) {
      expect(polyEval(coeffs, BigInt.from(pt['x'] as int)).toString(),
          pt['result_decimal']);
    }
    final pts = (f['lagrange_interpolate_at_zero']['points'] as List)
        .map((p) =>
            (BigInt.from((p as List)[0] as int), BigInt.parse(p[1] as String)))
        .toList();
    expect(lagrangeInterpolateAtZero(pts).toString(),
        f['lagrange_interpolate_at_zero']['secret_decimal']);
  });

  test('string_normalization', () {
    for (final c in (kat['string_normalization'] as List)
        .cast<Map<String, dynamic>>()) {
      final input = utf8.decode(hexDecode(c['input_utf8_hex']));
      expect(hexEncode(exactStringRecover(input)), c['normalized_utf8_hex']);
    }
  });

  test('aad canonical encoding', () {
    final v = kat['aad'] as Map<String, dynamic>;
    final state = PublicState.fromJson(v['state_json'] as Map<String, dynamic>);
    expect(hexEncode(state.computeAad()), v['aad_hex']);
  });

  test('aad survives toJson round trip', () {
    final v = kat['aad'] as Map<String, dynamic>;
    final state = PublicState.fromJson(v['state_json'] as Map<String, dynamic>);
    final reparsed = PublicState.fromJsonString(state.toJsonString());
    expect(hexEncode(reparsed.computeAad()), v['aad_hex']);
  });

  test('vault_unlock', () {
    final v = kat['vault_unlock'] as Map<String, dynamic>;
    final state = PublicState.fromJson(v['state_json'] as Map<String, dynamic>);
    final answers = (v['answers'] as List).cast<String>();

    expect(hexEncode(unlock(sodium, state, answers)!), v['mek_hex']);
    final oneWrong = List<String?>.from(answers)..[1] = 'WRONG';
    expect(hexEncode(unlock(sodium, state, oneWrong)!), v['mek_hex']);
    final oneMissing = List<String?>.from(answers)..[0] = null;
    expect(hexEncode(unlock(sodium, state, oneMissing)!), v['mek_hex']);
    expect(unlock(sodium, state, [answers[0], 'WRONG', null]), isNull);
  });

  test('vault_unlock_single_field (password vault)', () {
    final v = kat['vault_unlock_single_field'] as Map<String, dynamic>;
    final state = PublicState.fromJson(v['state_json'] as Map<String, dynamic>);
    expect(hexEncode(unlock(sodium, state, (v['answers'] as List).cast<String>())!),
        v['mek_hex']);
    expect(unlock(sodium, state, ['WRONG']), isNull);
  });

  test('vault_unlock_unicode', () {
    final v = kat['vault_unlock_unicode'] as Map<String, dynamic>;
    final state = PublicState.fromJson(v['state_json'] as Map<String, dynamic>);
    expect(hexEncode(unlock(sodium, state, (v['answers'] as List).cast<String>())!),
        v['mek_hex']);
    expect(
        hexEncode(
            unlock(sodium, state, (v['alt_answers'] as List).cast<String>())!),
        v['mek_hex']);
  });

  group('enroll (write side)', () {
    final fast = Params(argon2: const Argon2Params(opslimit: 1, memlimit: 8 * 1024 * 1024));

    test('round trip 2-of-3 with serialization', () {
      final mek = Uint8List.fromList(List.generate(32, (i) => i * 7 % 256));
      final state = enroll(sodium, mek, ['alpha', 'bravo', 'charlie'], 2,
          params: fast);
      final restored = PublicState.fromJsonString(state.toJsonString());
      expect(hexEncode(unlock(sodium, restored, ['alpha', 'WRONG', 'charlie'])!),
          hexEncode(mek));
      expect(unlock(sodium, restored, ['x', 'y', 'charlie']), isNull);
    });

    test('Dart-enrolled vault, M=1 password mode', () {
      final mek = Uint8List.fromList(List.generate(32, (i) => 255 - i));
      final state = enroll(sodium, mek, ['Pässwörd  '], 1, params: fast);
      // normalization applies at enroll too: variants unlock
      expect(hexEncode(unlock(sodium, state, ['pässwörd'])!), hexEncode(mek));
      expect(unlock(sodium, state, ['passwoerd']), isNull);
    });

    test('parameter guards', () {
      final mek = Uint8List(32);
      expect(() => enroll(sodium, mek, [], 1, params: fast),
          throwsArgumentError);
      expect(() => enroll(sodium, mek, ['a'], 2, params: fast),
          throwsArgumentError);
      expect(
          () => enroll(sodium, mek, ['a', 'b'], 1,
              params: Params(
                  argon2: const Argon2Params(
                      opslimit: 1, memlimit: 8 * 1024 * 1024, hashLen: 32))),
          throwsArgumentError);
    });
  });
}
