"""
Generate ports/dart_spike/lib/unicode_tables.dart from CPython's Unicode data.

ExactStringProcessor normalizes with NFC -> str.strip() -> str.casefold().
Dart has no built-in casefold (toLowerCase() is simple lowercasing, not full
case folding) and its trim() whitespace set differs from Python's strip().
Rather than approximate, we EXPORT the exact mappings from the same CPython
runtime that defines the reference behavior:

- kCasefold: every code point whose str.casefold() differs from itself
  (full case folding: one-to-many expansions like ß -> ss included).
- kPyWhitespace: every code point where str.isspace() is true (Python strip()
  semantics; differs from Dart trim(), e.g. Dart strips U+FEFF, Python not).

Regenerate when the reference Python version (and hence its Unicode tables)
changes: python -m tessera.tools.gen_dart_unicode
"""

from __future__ import annotations

import os
import sys


def main() -> int:
    casefold: list[tuple[int, str]] = []
    whitespace: list[int] = []
    for cp in range(0x110000):
        if 0xD800 <= cp <= 0xDFFF:  # surrogates: not valid scalar values
            continue
        ch = chr(cp)
        f = ch.casefold()
        if f != ch:
            casefold.append((cp, f))
        if ch.isspace():
            whitespace.append(cp)

    def dart_str(s: str) -> str:
        return "'" + "".join(f"\\u{{{ord(c):x}}}" for c in s) + "'"

    lines = [
        "// GENERATED by tessera/tools/gen_dart_unicode.py — DO NOT EDIT.",
        "// Exact str.casefold() and str.isspace() tables exported from the",
        f"// reference CPython {sys.version.split()[0]} (unicodedata "
        f"{__import__('unicodedata').unidata_version}).",
        "",
        f"const Map<int, String> kCasefold = {{",
    ]
    for cp, f in casefold:
        lines.append(f"  0x{cp:x}: {dart_str(f)},")
    lines.append("};")
    lines.append("")
    lines.append("const Set<int> kPyWhitespace = {")
    lines.append("  " + ", ".join(f"0x{cp:x}" for cp in whitespace))
    lines.append("};")
    lines.append("")

    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.abspath(
        os.path.join(here, "..", "ports", "dart_spike", "lib", "unicode_tables.dart")
    )
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print(f"wrote {out}: {len(casefold)} casefold entries, "
          f"{len(whitespace)} whitespace code points")
    return 0


if __name__ == "__main__":
    sys.exit(main())
